apiVersion: migration.openshift.io/v1alpha1
kind: MigrationController
metadata:
  name: migration-controller
  namespace: openshift-migration
spec:
  cluster_name: host
  migration_velero: true
  migration_controller: true
  migration_ui: true
  #Uncomment the following line for OpenShift 4.1
  #deprecated_cors_configuration: true
