---
mig_controller_image: quay.io/ocpmigrate/mig-controller
mig_controller_version: improved-copy-mig
mig_namespace: mig
mig_ui_configmap_name : mig-ui-config
mig_ui_oauth_user_scope: "user:full"
mig_ui_image: quay.io/ocpmigrate/mig-ui
mig_ui_version: latest
velero_aws_secret_name: cloud-credentials
velero_image: quay.io/ocpmigrate/velero:fusor-dev
velero_plugin_image: quay.io/ocpmigrate/migration-plugin:latest
restic_pv_host_path: /var/lib/kubelet/pods
# optional resource limits for controller
mig_controller_limits_memory: "300Mi"
mig_controller_limits_cpu: "100m"
mig_controller_requests_memory: "250Mi"
mig_controller_requests_cpu: "100m"
mig_svc_account: true
dedicated_admin_mode: false
