apiVersion: migration.openshift.io/v1alpha1
kind: MigrationController
metadata:
  name: example-migrationcontroller
spec:
  cluster_name: host
  migration_velero: true
  migration_controller: true
  migration_ui: false
  mig_ui_cluster_api_endpoint: https://nowhere.localhost:8443/api
  olm_managed: true
#ui uses openshift specific types that won't work in molecules kubernetes container
