---

- name: Converge
  hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
    deploy_dir: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/deploy"
    image_name: migration.openshift.io/mig-operator:testing
    custom_resource: "{{ lookup('file', '/'.join([deploy_dir, 'migration_v1alpha1_migration_cr.yaml'])) | from_yaml }}"
  tasks:
  - name: Create the migration.openshift.io/v1alpha1.MigrationController
    k8s:
      namespace: '{{ controller_namespace }}'
      definition: "{{ lookup('file', '/'.join([deploy_dir, 'migration_v1alpha1_migration_cr.yaml'])) }}"

  - name: Get the newly created Custom Resource
    debug:
      msg: "{{ lookup('k8s', group='migration.openshift.io', api_version='v1alpha1', kind='MigrationController', namespace=controller_namespace, resource_name=custom_resource.metadata.name) }}"

  - name: Wait 40s for reconciliation to run
    k8s_info:
      api_version: 'v1alpha1'
      kind: 'MigrationController'
      namespace: '{{ controller_namespace }}'
      name: '{{ custom_resource.metadata.name }}'
    register: reconcile_cr
    until:
    - "'Successful' in (reconcile_cr | json_query('resources[].status.conditions[].reason'))"
    delay: 4
    retries: 10

- import_playbook: '{{ playbook_dir }}/../default/asserts.yml'
